### ISSUE TITLE
hueRotate

### ISSUE THREAD

**Issue by fastCreator** [klouskingsley/imagedata-filters#1]
hueRotate  

得出来的结果和css filter 不一致

**Comment by fastCreator** [comment]
![image](https://user-images.githubusercontent.com/13810325/54903468-e7e61080-4f16-11e9-831a-992984b9ade8.png)

**Comment by fastCreator** [comment]
为什么这个文档a00不是这么计算的？

**Comment by klouskingsley** [comment]
你指的是精度吗，如果按照上面矩阵表达式是0.213和0.787，但是下面的表述是0.2127和0.7873。
imagedata-filtes是按照上面的矩阵表达式来算的。
